apiVersion: v1
kind: Pod
metadata:
  name: nginx-sample
spec:
  containers:
  - name: nginx-container
    image: nginx:1.25.1
    volumeMounts:
    - name: nginx-secret
      mountPath: /etc/config
  volumes:
  - name: nginx-secret
    secret:
      secretName: nginx-secret
---
apiVersion: v1
kind: Secret
metadata:
  name: nginx-secret
data:
  server.key: LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlFb3dJQkFBS0NBUUVBeVF0ZjhJV3RDV2lYV3laajNyU2dxYmMraVhrZGpYbFMzeDRNUDVQb3lMRkFCMGUvCk5rTy9HcTNZQXZiazRJR0Y1N0wxTnZYVExNWm1LK2RMNm0vZFlqZTFZRnFwd2M2QktwbkRFS1AzU0tZMk9DOW0KSkh3dWRRS0JnSHNnL01DU1hhUUlDK3FOWnJNS2NhaTc0VExqM0JEWC84NE5qM1RubmdHVG5DbGg5Q0U0ODZBNgpDUzBMNGRHeWNRV1VoRi94aVI2Um9TVGNsQUwxN3grQUNPS3BRZnhZczR1OGUrSXpqalJSdVBPcnBPaHQ3ZEI5CkxxdkpubmVpOURzQktJU0tHbXljYWMrcTJVdWY4L1RpSmpqVXVCd0xkZUh3bVB0U3dPN0cKLS0tLS1FTkQgUlNBIFBSSVZBVEUgS0VZLS0tLS0KCg==
